on: push
name: deployar
jobs:
  deploy:
    name: deployar en cluster
    runs-on: ububtu-latest
    steps:
    - uses: action/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
